export default function() {
	return [
		{
			id: 1,
			key: "573243N242220E",
			title: "Dabas liegums “Vidzemes akmeņainā jūrmala”",
			description:
				"Hiking along the Rocky Seashore of Vidzeme- one day tour in the Nature Reserve `Vidzeme rocky seaside`. One of the most beautiful parts of the Baltic sea seashore in Latvia. User interaction with 3d model of rocks brings dynamic user experience by being involved into multiple levels of perception of the scene and viewports.",
			component: "Water",
			images: [
				{
					src: `../../images/01.jpg`,
					id: 1,
				},
				{
					src: `../../images/02.jpg`,
					id: 2,
				},
				{
					src: `../../images/03.jpg`,
					id: 3,
				},
			],
		},
		{
			id: 2,
			key: "573243N242220F",
			title: "Art nouveau in RIGA",
			description: "Animated slideshow of- Art Nouveau architecture in Riga- makes up roughly one third of all buildings in the centre of Riga, making the capital the city of Latvia enriched with the highest concentration of Art Nouveau architecture as nowhere in the world.",
			component: "Art",
			images: [
				{
					src: `../../images/04.jpg`,
					id: 1,
				},
				{
					src: `../../images/05.jpg`,
					id: 2,
				},
				{
					src: `../../images/06.jpg`,
					id: 3,
				},
			],
			layers: [
				[
					{
						src: `../../images/artnouveau/1.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1.09,
						activeY: 1.05,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/111.png`,
						class: `carousel-img-2`,
						transform: `scale`,
						activeX: 1.05,
						activeY: 1.05,
						left: `0`,
						top: `auto`,
						bottom: `auto`,
						right: `auto`,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/1111.png`,
						class: `carousel-img-3`,
						transform: `scale`,
						activeX: 1.05,
						activeY: 1.05,
						right: `0`,
						top: `auto`,
						bottom: `auto`,
						left: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/1.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/111.png`,
						class: `carousel-img-2`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						left: 0,
						top: `auto`,
						bottom: `auto`,
						right: `auto`,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/1111.png`,
						class: `carousel-img-3`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						right: 0,
						top: `auto`,
						bottom: `auto`,
						left: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/3.png`,
						class: `carousel-img3`,
						transform: `scale`,
						activeX: 1.04,
						activeY: 1.04,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/33.png`,
						class: `carousel-img3-1`,
						transform: `scale`,
						activeX: 1.04,
						activeY: 1.04,
						left: 0,
						right: 0,
						top: `auto`,
						bottom: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/3.png`,
						class: `carousel-img3`,
						transform: `scale`,
						activeX: 1.02,
						activeY: 1.02,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/33.png`,
						class: `carousel-img3-1`,
						transform: `scale`,
						activeX: 1.02,
						activeY: 1.02,
						left: 0,
						right: 0,
						top: `auto`,
						bottom: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/3.png`,
						class: `carousel-img3`,
						transform: `scale`,
						activeX: 1.03,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/2.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1.065,
						activeY: 1.065,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/22.png`,
						class: `carousel-img2-2`,
						transform: `scale`,
						activeX: 1.05,
						activeY: 1.04,
						left: 0,
						top: `auto`,
						bottom: `auto`,
						right: `auto`,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/222.png`,
						class: `carousel-img2-3`,
						transform: `scale`,
						activeX: 1.05,
						activeY: 1.04,
						right: 0,
						top: `auto`,
						bottom: `auto`,
						left: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/2.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1.06,
						activeY: 1.06,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/22.png`,
						class: `carousel-img2-2`,
						transform: `scale`,
						activeX: 1.06,
						activeY: 1.06,
						left: 0,
						top: `auto`,
						bottom: `auto`,
						right: `auto`,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/222.png`,
						class: `carousel-img2-3`,
						transform: `scale`,
						activeX: 1.06,
						activeY: 1.06,
						right: 0,
						top: `auto`,
						bottom: `auto`,
						left: `auto`,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/2.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1.04,
						activeY: 1.04,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/4.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/4.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1.05,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/5.png`,
						class: `carousel-img5`,
						transform: `scale`,
						deg: 0,
						rotate: true,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/5.png`,
						class: `carousel-img5`,
						transform: `scale`,
						deg: 20,
						rotate: true,
						activeX: 1.42,
						activeY: 1.42,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/6.png`,
						class: `carousel-img5`,
						transform: `scale`,
						activeX: 1.4,
						activeY: 1.4,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/6.png`,
						class: `carousel-img5`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/7.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1.03,
						activeY: 1.03,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/777.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1.09,
						activeY: 1.06,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/7.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
					{
						src: `../../images/artnouveau/777.png`,
						class: `carousel-img2`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						margin: `auto`,
						width: `100%`,
					},
				],
				[
					{
						src: `../../images/artnouveau/8.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1.55,
						activeY: 1.55,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
				[
					{
						src: `../../images/artnouveau/9.png`,
						class: `carousel-img`,
						transform: `scale`,
						activeX: 1,
						activeY: 1,
						top: 0,
						bottom: 0,
						left: 0,
						right: 0,
						width: `100%`,
						margin: `auto`,
					},
				],
			],
		},
	]
}
